// Code generated by @ui8kit/codegen. DO NOT EDIT.

package formswitch

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed switch.variants.json
var switchVariantsJSON []byte

// SwitchVariants is the CVA recipe shared verbatim by all runtimes.
var SwitchVariants = utils.MustParseVariantRecipe(switchVariantsJSON).ToVariants()
