// Code generated by @ui8kit/codegen. DO NOT EDIT.

package group

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed group.variants.json
var groupVariantsJSON []byte

// GroupVariants is the CVA recipe shared verbatim by all runtimes.
var GroupVariants = utils.MustParseVariantRecipe(groupVariantsJSON).ToVariants()
