// Code generated by @ui8kit/codegen. DO NOT EDIT.

package box

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed box.variants.json
var boxVariantsJSON []byte

// BoxVariants is the CVA recipe shared verbatim by all runtimes.
var BoxVariants = utils.MustParseVariantRecipe(boxVariantsJSON).ToVariants()
