// Code generated by @ui8kit/codegen. DO NOT EDIT.

package block

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed block.variants.json
var blockVariantsJSON []byte

// BlockVariants is the CVA recipe shared verbatim by all runtimes.
var BlockVariants = utils.MustParseVariantRecipe(blockVariantsJSON).ToVariants()
