// Code generated by @ui8kit/codegen. DO NOT EDIT.

package radio

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed radio.variants.json
var radioVariantsJSON []byte

// RadioVariants is the CVA recipe shared verbatim by all runtimes.
var RadioVariants = utils.MustParseVariantRecipe(radioVariantsJSON).ToVariants()
