// Code generated by @ui8kit/codegen. DO NOT EDIT.

package link

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed link.variants.json
var linkVariantsJSON []byte

// LinkVariants is the CVA recipe shared verbatim by all runtimes.
var LinkVariants = utils.MustParseVariantRecipe(linkVariantsJSON).ToVariants()
