// Code generated by @ui8kit/codegen. DO NOT EDIT.

package dialog

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed dialog.variants.json
var dialogVariantsJSON []byte

// DialogVariants is the CVA recipe shared verbatim by all runtimes.
var DialogVariants = utils.MustParseVariantRecipe(dialogVariantsJSON).ToVariants()
