// Code generated by @ui8kit/codegen. DO NOT EDIT.

package checkbox

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed checkbox.variants.json
var checkboxVariantsJSON []byte

// CheckboxVariants is the CVA recipe shared verbatim by all runtimes.
var CheckboxVariants = utils.MustParseVariantRecipe(checkboxVariantsJSON).ToVariants()
