// Code generated by @ui8kit/codegen. DO NOT EDIT.

package inline

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed inline.variants.json
var inlineVariantsJSON []byte

// InlineVariants is the CVA recipe shared verbatim by all runtimes.
var InlineVariants = utils.MustParseVariantRecipe(inlineVariantsJSON).ToVariants()
