// Code generated by @ui8kit/codegen. DO NOT EDIT.

package textarea

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed textarea.variants.json
var textareaVariantsJSON []byte

// TextareaVariants is the CVA recipe shared verbatim by all runtimes.
var TextareaVariants = utils.MustParseVariantRecipe(textareaVariantsJSON).ToVariants()
