// Code generated by @ui8kit/codegen. DO NOT EDIT.

package grid

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed grid.variants.json
var gridVariantsJSON []byte

// GridVariants is the CVA recipe shared verbatim by all runtimes.
var GridVariants = utils.MustParseVariantRecipe(gridVariantsJSON).ToVariants()
