// Code generated by @ui8kit/codegen. DO NOT EDIT.

package linebreak

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed linebreak.variants.json
var linebreakVariantsJSON []byte

// LinebreakVariants is the CVA recipe shared verbatim by all runtimes.
var LinebreakVariants = utils.MustParseVariantRecipe(linebreakVariantsJSON).ToVariants()
