// Code generated by @ui8kit/codegen. DO NOT EDIT.

package disclosure

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed disclosure.variants.json
var disclosureVariantsJSON []byte

// DisclosureVariants is the CVA recipe shared verbatim by all runtimes.
var DisclosureVariants = utils.MustParseVariantRecipe(disclosureVariantsJSON).ToVariants()

//go:embed summary.variants.json
var summaryVariantsJSON []byte

// SummaryVariants is the CVA recipe shared verbatim by all runtimes.
var SummaryVariants = utils.MustParseVariantRecipe(summaryVariantsJSON).ToVariants()
