// Code generated by @ui8kit/codegen. DO NOT EDIT.

package iconbadge

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed iconbadge.variants.json
var iconbadgeVariantsJSON []byte

// IconbadgeVariants is the CVA recipe shared verbatim by all runtimes.
var IconbadgeVariants = utils.MustParseVariantRecipe(iconbadgeVariantsJSON).ToVariants()
