// Code generated by @ui8kit/codegen. DO NOT EDIT.

package container

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed container.variants.json
var containerVariantsJSON []byte

// ContainerVariants is the CVA recipe shared verbatim by all runtimes.
var ContainerVariants = utils.MustParseVariantRecipe(containerVariantsJSON).ToVariants()
