// Code generated by @ui8kit/codegen. DO NOT EDIT.

package list

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed list.variants.json
var listVariantsJSON []byte

// ListVariants is the CVA recipe shared verbatim by all runtimes.
var ListVariants = utils.MustParseVariantRecipe(listVariantsJSON).ToVariants()
