// Code generated by @ui8kit/codegen. DO NOT EDIT.

package stack

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed stack.variants.json
var stackVariantsJSON []byte

// StackVariants is the CVA recipe shared verbatim by all runtimes.
var StackVariants = utils.MustParseVariantRecipe(stackVariantsJSON).ToVariants()
