// Code generated by @ui8kit/codegen. DO NOT EDIT.

package alert

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed alert.variants.json
var alertVariantsJSON []byte

// AlertVariants is the CVA recipe shared verbatim by all runtimes.
var AlertVariants = utils.MustParseVariantRecipe(alertVariantsJSON).ToVariants()
