// Code generated by @ui8kit/codegen. DO NOT EDIT.

package title

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed title.variants.json
var titleVariantsJSON []byte

// TitleVariants is the CVA recipe shared verbatim by all runtimes.
var TitleVariants = utils.MustParseVariantRecipe(titleVariantsJSON).ToVariants()
