// Code generated by @ui8kit/codegen. DO NOT EDIT.

package badge

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed badge.variants.json
var badgeVariantsJSON []byte

// BadgeVariants is the CVA recipe shared verbatim by all runtimes.
var BadgeVariants = utils.MustParseVariantRecipe(badgeVariantsJSON).ToVariants()
