// Code generated by @ui8kit/codegen. DO NOT EDIT.

package text

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed text.variants.json
var textVariantsJSON []byte

// TextVariants is the CVA recipe shared verbatim by all runtimes.
var TextVariants = utils.MustParseVariantRecipe(textVariantsJSON).ToVariants()
