// Code generated by @ui8kit/codegen. DO NOT EDIT.

package card

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed card.variants.json
var cardVariantsJSON []byte

// CardVariants is the CVA recipe shared verbatim by all runtimes.
var CardVariants = utils.MustParseVariantRecipe(cardVariantsJSON).ToVariants()
