// Code generated by @ui8kit/codegen. DO NOT EDIT.

package form

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed fieldset.variants.json
var fieldsetVariantsJSON []byte

// FieldsetVariants is the CVA recipe shared verbatim by all runtimes.
var FieldsetVariants = utils.MustParseVariantRecipe(fieldsetVariantsJSON).ToVariants()

//go:embed legend.variants.json
var legendVariantsJSON []byte

// LegendVariants is the CVA recipe shared verbatim by all runtimes.
var LegendVariants = utils.MustParseVariantRecipe(legendVariantsJSON).ToVariants()

//go:embed meter.variants.json
var meterVariantsJSON []byte

// MeterVariants is the CVA recipe shared verbatim by all runtimes.
var MeterVariants = utils.MustParseVariantRecipe(meterVariantsJSON).ToVariants()

//go:embed progress.variants.json
var progressVariantsJSON []byte

// ProgressVariants is the CVA recipe shared verbatim by all runtimes.
var ProgressVariants = utils.MustParseVariantRecipe(progressVariantsJSON).ToVariants()
