// Code generated by @ui8kit/codegen. DO NOT EDIT.

package form

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed form.variants.json
var formVariantsJSON []byte

// FormVariants is the CVA recipe shared verbatim by all runtimes.
var FormVariants = utils.MustParseVariantRecipe(formVariantsJSON).ToVariants()

//go:embed form-item.variants.json
var formItemVariantsJSON []byte

// FormItemVariants is the CVA recipe shared verbatim by all runtimes.
var FormItemVariants = utils.MustParseVariantRecipe(formItemVariantsJSON).ToVariants()

//go:embed form-description.variants.json
var formDescriptionVariantsJSON []byte

// FormDescriptionVariants is the CVA recipe shared verbatim by all runtimes.
var FormDescriptionVariants = utils.MustParseVariantRecipe(formDescriptionVariantsJSON).ToVariants()

//go:embed form-message.variants.json
var formMessageVariantsJSON []byte

// FormMessageVariants is the CVA recipe shared verbatim by all runtimes.
var FormMessageVariants = utils.MustParseVariantRecipe(formMessageVariantsJSON).ToVariants()
