// Code generated by @ui8kit/codegen. DO NOT EDIT.

package input

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed input.variants.json
var inputVariantsJSON []byte

// InputVariants is the CVA recipe shared verbatim by all runtimes.
var InputVariants = utils.MustParseVariantRecipe(inputVariantsJSON).ToVariants()
