// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Host(props HostProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script id=\"fastygo-dev-overlay-loader\" data-request-id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(props.RequestID)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/devoverlay/ui/widget.templ`, Line: 4, Col: 74}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" data-i18n=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(props.PanelJSON)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/devoverlay/ui/widget.templ`, Line: 4, Col: 104}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\">\r\n\t\t(() => {\r\n\t\t\tconst currentScript = document.currentScript;\r\n\t\t\tif (!currentScript) return;\r\n\t\t\twindow.__FASTYGO_DEV_OVERLAY__ = {\r\n\t\t\t\trequestId: currentScript.dataset.requestId || \"\",\r\n\t\t\t\ti18n: currentScript.dataset.i18n || \"\",\r\n\t\t\t};\r\n\t\t\tif (window.matchMedia?.(\"(max-width: 767px)\").matches) return;\r\n\t\t\tif (window.__FASTYGO_DEV_OVERLAY_MOUNT__) {\r\n\t\t\t\twindow.__FASTYGO_DEV_OVERLAY_MOUNT__();\r\n\t\t\t\treturn;\r\n\t\t\t}\r\n\t\t\tif (document.querySelector(\"script[data-fastygo-dev-overlay-bundle]\")) return;\r\n\r\n\t\t\tconst script = document.createElement(\"script\");\r\n\t\t\tscript.async = false;\r\n\t\t\tscript.src = \"/__fastygo/dev/overlay.js\";\r\n\t\t\tscript.dataset.fastygoDevOverlayBundle = \"\";\r\n\t\t\tscript.dataset.requestId = currentScript.dataset.requestId || \"\";\r\n\t\t\tscript.dataset.i18n = currentScript.dataset.i18n || \"\";\r\n\t\t\tscript.onload = () => window.__FASTYGO_DEV_OVERLAY_MOUNT__?.();\r\n\t\t\tcurrentScript.after(script);\r\n\t\t})();\r\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
