// Code generated by @ui8kit/codegen. DO NOT EDIT.

package selectfield

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed select.variants.json
var selectVariantsJSON []byte

// SelectVariants is the CVA recipe shared verbatim by all runtimes.
var SelectVariants = utils.MustParseVariantRecipe(selectVariantsJSON).ToVariants()
