// Code generated by @ui8kit/codegen. DO NOT EDIT.

package separator

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed separator.variants.json
var separatorVariantsJSON []byte

// SeparatorVariants is the CVA recipe shared verbatim by all runtimes.
var SeparatorVariants = utils.MustParseVariantRecipe(separatorVariantsJSON).ToVariants()
