// Code generated by @ui8kit/codegen. DO NOT EDIT.

package table

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed table.variants.json
var tableVariantsJSON []byte

// TableVariants is the CVA recipe shared verbatim by all runtimes.
var TableVariants = utils.MustParseVariantRecipe(tableVariantsJSON).ToVariants()
