// Code generated by @ui8kit/codegen. DO NOT EDIT.

package image

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed image.variants.json
var imageVariantsJSON []byte

// ImageVariants is the CVA recipe shared verbatim by all runtimes.
var ImageVariants = utils.MustParseVariantRecipe(imageVariantsJSON).ToVariants()
