// Code generated by @ui8kit/codegen. DO NOT EDIT.

package button

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed button.variants.json
var buttonVariantsJSON []byte

// ButtonVariants is the CVA recipe shared verbatim by all runtimes.
var ButtonVariants = utils.MustParseVariantRecipe(buttonVariantsJSON).ToVariants()
