// Code generated by @ui8kit/codegen. DO NOT EDIT.

package label

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed label.variants.json
var labelVariantsJSON []byte

// LabelVariants is the CVA recipe shared verbatim by all runtimes.
var LabelVariants = utils.MustParseVariantRecipe(labelVariantsJSON).ToVariants()
