// Code generated by @ui8kit/codegen. DO NOT EDIT.

package icon

import (
	_ "embed"

	utils "github.com/fastygo/blank/internal/kit/utils"
)

//go:embed icon.variants.json
var iconVariantsJSON []byte

// IconVariants is the CVA recipe shared verbatim by all runtimes.
var IconVariants = utils.MustParseVariantRecipe(iconVariantsJSON).ToVariants()
